/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function hasFiles(): boolean
export declare function getFiles(): Array<string>
export declare function hasImage(): boolean
export declare function hasHtml(): boolean
export declare function hasRtf(): boolean
export declare function hasText(): boolean
export declare function getText(): string
export declare function getRtf(): string
export declare function getHtml(): string
